### ISSUE TITLE
Error "undefined undefined" with neo4j 2.2.3

### ISSUE THREAD

**Issue by nireak** [maxdemarzi/neo_hpce#2]
Hi Max,

When I have upgrade neo4j to version 2.2.3 I get an error "undefined-undefined" even with helloworld

:GET /v1/service/helloworld
Error: undefined - undefined
 Request error

Any clues about what could be the reason? Thank you

**Comment by maxdemarzi** [comment]
If you build the jar using 2.1.3 and copy it to a 2.2.3 server it works fine. If you try the code with 2.2.3 it's a mess since a whole bunch of stuff got deprecated. I'm thinking of redoing these with 2.3 instead.

**Comment by nireak** [comment]
Thank you Max for your answer.
I'm afraid I must be doing something wrong because although I have compiled now with neo4j version 2.1.3 (changing the value at pom.xml) when I copy the jar extension to a 2.2.3 server I still get the same "undefined" error.
I'm newbie to java.... Do you know how can I check if I have the right dependencies?
